### ISSUE TITLE
Function 'align_arr' in 'project-aligned-trees.py' breaks with input CoNLLU file

### ISSUE THREAD

**Issue by Jbar-ry** [ftyers/cross-lingual-parsing#3]
Firstly, thanks for the great resource!

I am trying to project output predicted by `UDPipe` into the target language Faroese.

Following the information in the [faroese data section](https://github.com/ftyers/cross-lingual-parsing/tree/master/data/faroese), it is recommended that I use `project-aligned-trees.py`.

Based on the below usage example:

```
if len(sys.argv) < 3: 
	print('python3 project-aligned-trees.py <conllu output> <alignments> <parallel text>')
	sys.exit(-1)
```

Using Swedish as an example source language, I am running this file with: 

```
python3 utils/project-aligned-trees.py data/faroese/fao_wiki.apertium.fao-swe.udpipe.parsed.conllu data/faroese/fao_wiki.apertium.fao-swe.align.txt data/faroese/fao_wiki.apertium.swe-fao.input.txt

```

However, the script `project-aligned-trees.py` breaks, seemingly from trying to parse the comment/metadata lines: 

```
Traceback (most recent call last):
  File "utils/project-aligned-trees.py", line 203, in <module>
    main(align, ud, corpora)
  File "utils/project-aligned-trees.py", line 182, in main
    align_res = align_arr(align)
  File "utils/project-aligned-trees.py", line 37, in align_arr
    p0 = int(pattern[0])
ValueError: invalid literal for int() with base 10: '#'

```

I'm just wondering am I doing something wrong or using a wrong input file? Apologies if I've missed something!

**Comment by ftyers** [comment]
Hey there! Can you show what you have in each of the input files? e.g. just `head -5` them.

**Comment by Jbar-ry** [comment]
Hi Fran! Sure. I am using the same files which are present in `cross-lingual-parsing/data/faroese` after pulling the repository. 


1. conllu output

```
head -5 data/faroese/fao_wiki.apertium.fao-swe.udpipe.parsed.conllu
```

```
# newdoc
# newpar
# sent_id = 1
# text = Färöarna ligger i Nordsjön, 280 km nordenfor till Shetland, 430 km från Island och 575 km vestfor till Norge.
1       Färöarna        Färö    NOUN    NN|UTR|PLU|DEF|NOM      Case=Nom|Definite=Def|Gender=Com|Number=Plur    2       nsubj   _       _

```

2. alignments 

```
head -5 data/faroese/fao_wiki.apertium.fao-swe.align.txt
```

```
0-0 1-1 2-2 3-3 4-4 5-5 6-6 7-7 8-8 9-9 10-10 11-11 12-12 13-13 14-14 15-15 16-16 17-17 18-18 19-19 20-20 21-21
0-0 1-1 2-2 3-3 4-4 5-5 6-6 7-7 8-8 9-9 10-10 11-11 12-12 13-13 14-14 15-15 16-16 17-17 18-18 19-19
0-0 1-0 2-1 3-2 4-3 5-4 6-5 7-7 8-9 8-10 9-11 10-12 11-13 12-14 13-15 14-16 15-17 16-18 17-19 18-20 19-21 20-22 21-23 22-24 23-25 24-26
0-0 1-1 2-2 3-3 4-4 5-5 6-6 7-7 8-8 9-9 10-10 11-11 12-12 13-13 14-14 15-15 16-16 17-17 18-18 19-19 20-21 21-22
0-0 1-1 2-2 3-3 4-4 5-5 6-6 7-7 8-8 9-9 10-10 11-11 12-12 13-13 14-14 15-12 15-15 16-16 17-17 18-18 20-19 21-20 22-21 23-21 24-22 25-22 26-23
```

3. parallel text

```
head -5 data/faroese/fao_wiki.apertium.swe-fao.input.txt
```

```
Färöarna ligger i Nordsjön , 280 km nordenfor till Shetland , 430 km från Island och 575 km vestfor till Norge . ||| ﻿Føroyar liggja í Norðuratlantshavi , 280 km norðan fyri Hetland , 430 km frá Íslandi og 575 km vestan fyri Noreg .
Fiskivinnan är den týdningarmesta inntøkukeldan i Färöarna , och hon omslynger om 95 % av all export ur Färöarna . ||| Fiskivinnan er tann týdningarmesta inntøkukeldan í Føroyum , og hon fevnir um 95 % av øllum útflutningi úr Føroyum .
När istiderna var av om år 12 000-10 000 f.Kr. , kom Färöarna från isen , fast än låg dej ubebyggede i många tusen år . ||| Tá ið ístíðirnar vóru av um ár 12 000-10 000 f.Kr. , komu Føroyar undan ísinum , men enn lógu tær óbygdar í nógv túsund ár .
Efter att isen var lagad , kom gróðurin omsider , buren av havstreymum och vinna , och lack och dalar var knappet . ||| Eftir at ísurin var horvin , kom gróðurin umsíðir , borin av havstreymum og vindi , og líðir og dalar vallaðust .
Den kom till Storbritannien , derfra seglade den i sex dagar nordover och då østover och kom till land att den nämnde  "Thule ". ||| Hann kom til Bretlands , haðan sigldi hann í seks dagar norðureftir og síðani eystureftir og kom til land , ið hann nevndi  "Thule " .

```

**Comment by ftyers** [comment]
Try removing the comments from the CoNLL-U file? 
`ValueError: invalid literal for int() with base 10: '#'` this looks like an error related to that.

**Comment by Jbar-ry** [comment]
Thanks, I tried something similar in the code for `project-aligned-trees.py` before opening the issue in a clone of the repository, e.g.:

```
    for line in align:
        if line.startswith("#"):
            continue # can we skip comment lines?

        d = {}
        print(line)
```

but I got a bug:

```
1       Färöarna        Färö    NOUN    NN|UTR|PLU|DEF|NOM      Case=Nom|Definite=Def|Gender=Com|Number=Plur    2       nsubj   _       _

Traceback (most recent call last):
  File "utils/project-aligned-trees.py", line 207, in <module>
    main(align, ud, corpora)
  File "utils/project-aligned-trees.py", line 186, in main
    align_res = align_arr(align)
  File "utils/project-aligned-trees.py", line 42, in align_arr
    p1 = int(pattern[1])
IndexError: list index out of range
```

Without touching any code (on an unchanged clone of the repository) and just removing comment lines from the conllu file, I seem to get the same error:

```
awk '!/^#/' data/faroese/fao_wiki.apertium.fao-swe.udpipe.parsed.conllu > data/faroese/swe_no_comment_test.conllu

head -5 data/faroese/swe_no_comment_test.conllu

1       Färöarna        Färö    NOUN    NN|UTR|PLU|DEF|NOM      Case=Nom|Definite=Def|Gender=Com|Number=Plur    2       nsubj   _       _
2       ligger  ligga   VERB    VB|PRS|AKT      Mood=Ind|Tense=Pres|VerbForm=Fin|Voice=Act      0       root    _       _
3       i       i       ADP     PP      _       4       case    _       _
4       Nordsjön        Nordsjön        PROPN   PM|NOM  Case=Nom        2       obl     _       SpaceAfter=No
5       ,       ,       PUNCT   MID     _       2       punct   _       _

```

```
python3 utils/project-aligned-trees.py data/faroese/swe_no_comment_test.conllu data/faroese/fao_wiki.apertium.fao-swe.align.txt data/faroese/fao_wiki.apertium.swe-fao.input.txt

Traceback (most recent call last):
  File "utils/project-aligned-trees.py", line 203, in <module>
    main(align, ud, corpora)
  File "utils/project-aligned-trees.py", line 182, in main
    align_res = align_arr(align)
  File "utils/project-aligned-trees.py", line 38, in align_arr
    p1 = int(pattern[1])
IndexError: list index out of range

```

**Comment by Jbar-ry** [comment]
Ok, I think I figured out the problem!

The variable names in the current version of the file need to be changed to match the correct order of the arguments passed on the command line, e.g. based on the usage example, instead of: 

```
align = open(sys.argv[1], 'r').readlines()
ud = open(sys.argv[2], 'r').readlines()
corpora = open(sys.argv[3], 'r').readlines()
```
It needs to be
```
ud = open(sys.argv[1], 'r').readlines()
align = open(sys.argv[2], 'r').readlines()
corpora = open(sys.argv[3], 'r').readlines()
```

Which makes sense as the `align_arr` function doesn't handle regular connlu file processing!

Thanks for your help!

**Comment by ftyers** [comment]
No problem! I fixed it in the repo too! :) Thanks for the report.

**Comment by jbrry** [comment]
No worries! thanks for updating Fran :)
